name: Upload to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: pypi-github-sync
      uses: PabloLec/pypi-github-sync@v1.0.1
      with:
          github_repo: javi-aranda/edx-analytics-logger
          twine_username: ${{ secrets.TWINE_USERNAME }}
          twine_password: ${{ secrets.TWINE_PASSWORD }}
          verify_metadata: true
          skip_existing: true
          verbose: true
